---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative-pg
        property: pgusername
    - secretKey: password
      remoteRef:
        key: cloudnative-pg
        property: pgpassword
    - secretKey: aws-access-key-id
      remoteRef:
        key: cloudnative-pg
        property: aws-access-key-id
    - secretKey: aws-secret-access-key
      remoteRef:
        key: cloudnative-pg
        property: aws-secret-access-key
