ansible_become_pass: ENC[AES256_GCM,data:SI2UPinDHHVS,iv:i8k4kjLjGmY4PXw3MOh/UnS+sHw7GpwzaUdACLRZMtQ=,tag:abzrLSbTA+jfq7G24+bfrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaFgvdkl1Q1pGUysvNit4
            R0FqbVd3b2gwS2dsb2w2VkZCVDdWV2RNQVhzClF6cnN1QVFSQmE0V3lmOHB1M0pJ
            V1hmNlNBUUwvT0ljTjdwOHFLZmNOaDgKLS0tIHBXaGVFUVBWblBNK295Z3MrS2h3
            UG81bXBRNEtCaWdWY3AxWEloRTNYWDAK2bNoRM5u2Tlv7NpV2lyLpUrd5xrTlLA9
            mngd4rvg6pru0VxO79Su1wN5DwS4G8e3EjzyV2DOVo7sIgtInbETJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T10:31:22Z"
    mac: ENC[AES256_GCM,data:NWj7ONlldcm8X7rmyVSAVnxm1EloYw9sHyB0qIfiLEVBQxPxTxBwSs+SwjWjAl0zQ7kmStWP+u8dh73v+kbu/I8gZb/rJhTO/PrHqVaGyqjOmAPz8zhEnPtGd0nAh5RSzr4C89oyleg3rQBXIymcmMNlTwdgqKMDAiTC4sUudn0=,iv:OX5Su0uK+revL88hdefZ5rb3XouWFAJYm7Fz4w4y/vA=,tag:eStlkTZHC/mdLyf3aJySBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
