---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./aquasec.yaml
  - ./authentik.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./falco.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-at-home-charts.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./longhorn.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./tyzbit.yaml
  - ./weave-gitops.yaml
