---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:

    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.12.4@sha256:d4b2306a6c34fdb82e8c1b2a61e71797a201664d7a7b0b602f8a524ef5e2b641

    env:
      TZ: "America/New_York"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "tautulli.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tautulli.${INTERNAL_DOMAIN}"
          - secretName: tautulli-tls

    service:
      main:
        ports:
          http:
            port: 8181

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config-v1

    resources:
      requests:
        memory: 142M
        cpu: 15m
      limits:
        memory: 1809M
        cpu: 150m
