apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSzc5Yi90cCt2TDduc3p4
            L3FtdG8yZUdiOHNJeXBzMFlWaGduR2l0VGdzCjVEYlBUazdLNFRLeHU5OHRReDhr
            Y3VjdEhLVytQMkowUHp6ODlDNVNuMW8KLS0tICtBbkZLYmRZVDRGR1FIZ3dnZkFI
            WW9SYmRmeHYrakhwSDFWdWpkV2E4RlEK2Ohd1Jm7nLhX9umnV9GPMm8v6Flc9MEN
            LuOn0kCerijdRJtW8mqqNspj42eXsO8k80M9oRudQLUWUDfgwA916g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T10:31:57Z"
    mac: ENC[AES256_GCM,data:6aaarJHtbLjA2lA2JL7L4KH5hD4QkL9gLD1/vyENFjyjIyuABCaPek/qWwDlq16PFj4AInl+092ykbu2KLZbt+a00mKSRGWI0URrfH3xWqxQWqnumHyyjC1/6iGXE76fQNXmovg5mljoGLxYGZnIdr3KMRs8XIWcrDjlLvwgUDw=,iv:9MWPNH2nZ7JWBe9Uxp8l3yjdwVbCnfdWr8ZdwB987/U=,tag:wML3KQHBdszsyeuB7Pd8pQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
