---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    ns: vpn
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    ns: test
    vpn-routed-gateway: "true"
    routed-gateway: "true"
