---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-authentik-postgresql-0
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-authentik-redis-master-0
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-database
