apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:XDXkTZH5vrJ6sqWANBy1Wyb1,iv:zysD95GSytqRdCanCmc3dtUh3q5q6ei6L0vIS9qm400=,tag:M9631Eg+GTDpukPGRc496Q==,type:str]
    api-key: ENC[AES256_GCM,data:eBWZ6DWlZkORFcmy7IcqCDTcRGbcPDLLhHki2QvX8wqdnLcKtQ==,iv:csb7PSz+2unqE1M+hlqkPw7DogdZC/e+wyVXyuCeNbg=,tag:dwoeNLe1MPeQR4DQFntxnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaGxiSFltQkFROVNwbk5I
            bmdFVVZtc0hXMy85d2FEM2UzRGxpL3k1cVQ0Ck42WGhZZFNmZVp3ems2dGVORVU5
            N0tNYzlHRVg3bEhhR3pjeGZ3eUpZM0EKLS0tIElpWUdPYklwVldkNXFnWG5Hb2tn
            VFljTUJnWVBZZWoydmNQSmRnOS9iWlUKlFq7JmT9jk7G8aoG13QB6pCSe06BwS0u
            Im4zlznyr4nDgHHKUFxAbVBdWvTGSSM5IYzJBNLl2Vwm6excQfs3wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T10:58:15Z"
    mac: ENC[AES256_GCM,data:gs8GhcMO1EV/5nUr121gw14/3cJWz5CIKCgZb2Gp+j3ZZO0trNT9amYCfcMuBea9S0T1oeJqj2kzMNBScfydfFV3dbacwSUBY4ytoq+/r8ZjWiN6CbyittgwCz1cClPnYzNZsa/JageOSB4iA7nN15JmZ13xoIaolTaaH4H1YaQ=,iv:Mwu4SwlDNL6J4DcyvCXv0MRo0eq+a23GpZGdexRIWjQ=,tag:Y9kEn9cBY+ILdpCrm//okA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
