---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m


  # dependsOn:
  #   - name: pod-gateway
  #     namespace: vpn

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:

    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.7.3.3759

    env:
      TZ: "America/New_York"
      PROWLARR__AUTHENTICATION_METHOD: External
    service:
      main:
        ports:
          http:
            port: 9696

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "prowlarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "prowlarr.${INTERNAL_DOMAIN}"
          - secretName: prowlarr-tls

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [44, 109, 10000]

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config

      backup:
        enabled: true
        readOnly: false
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS2_ADDR}"
            path: /volume1/Kubernetes/prowlarr
        mountPath: /config/Backups

    resources:
      requests:
        memory: 266M
        cpu: 10m
      limits:
        memory: 3429M
        cpu: 150m
