---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pod-gateway-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pod-gateway
