---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: weave-gitops-secret
    creationPolicy: Owner
  data:
    - secretKey: adminPassword
      remoteRef:
        key: weave-gitops
        property: adminPassword
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-user-auth
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cluster-user-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: weave-gitops
        property: username
    - secretKey: password
      remoteRef:
        key: weave-gitops
        property: adminPassword
