---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:

    defaultSettings:
      defaultReplicaCount: 3
      backupTarget: ${NFS_BACKUP}
      # Below requires that nodes used for storage have the label
      # node.longhorn.io/create-default-disk=true
      createDefaultDiskLabeledNodes: true
      storageOverProvisioningPercentage: 150
      storageMinimalAvailablePercentage: 50
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      defaultDataPath: /var/lib/longhorn
      restoreVolumeRecurringJobs: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn

    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.${INTERNAL_DOMAIN}
      tls: true
      tlsSecret: longhorn.local-tls
