---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  dependsOn:
    - name: longhorn
      namespace: storage

  uninstall:
    keepHistory: false

  values:

    image:
      repository: ghcr.io/onedr0p/lidarr-develop
      tag: 1.3.3.3432@sha256:45804b8d819bdbf1dc1fc365894d29f11d09da4a2d5581360bcfa09af6aef96a

    service:
      main:
        ports:
          http:
            port: 8686

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host lidarr.${INTERNAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: lidarr-tls
        tls:
          - hosts:
              - *host
            secretName: lidarr-tls

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 105
        - 100

    persistence:

      config:
        enabled: true
        existingClaim: lidarr-config

      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/Media/Music
        mountPath: /media

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    resources:
      requests:
        cpu: 200m
        memory: 700Mi
      limits:
        cpu: 500m
        memory: 1Gi

